default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING

development:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: moviekws_development

test:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: moviekws_test
  
production:
  <<: *default
  host: db
  port: 5432
  username: postgres
  database: moviekws_production